# Generated by Django 5.1.7 on 2026-03-12 00:52

import django.core.validators
import django.db.models.deletion
import propuestas.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("empresas", "0030_fideicomiso_empresas_relacionadas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Propuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_propuesta",
                    models.CharField(
                        choices=[("CF", "Carta Fianza"), ("FD", "Fideicomiso")],
                        max_length=2,
                    ),
                ),
                (
                    "empresa_nombre_snapshot",
                    models.CharField(blank=True, max_length=200),
                ),
                ("es_consorcio_snapshot", models.BooleanField(default=False)),
                (
                    "representante_legal_snapshot",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "dni_representante_snapshot",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Solo se permiten letras, números y guiones.",
                                regex="^[0-9A-Za-z\\-]+$",
                            )
                        ],
                    ),
                ),
                ("facturador_texto", models.CharField(max_length=200)),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[("S/", "Soles"), ("$", "Dólares"), ("€", "Euros")],
                        default="S/",
                        max_length=3,
                    ),
                ),
                (
                    "comision_monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("comision_fecha", models.DateField()),
                (
                    "comision_moneda",
                    models.CharField(
                        choices=[("S/", "Soles"), ("$", "Dólares"), ("€", "Euros")],
                        default="S/",
                        max_length=3,
                    ),
                ),
                (
                    "comision_tipo",
                    models.CharField(
                        choices=[
                            ("IGV", "IGV"),
                            ("SIN_IGV", "Sin IGV"),
                            ("CON_RET", "Con retención"),
                        ],
                        default="IGV",
                        max_length=10,
                    ),
                ),
                (
                    "comision_cuenta",
                    models.CharField(
                        choices=[
                            ("BBVA", "BBVA"),
                            ("INTERBANK", "Interbank"),
                            ("BCP", "BCP"),
                            ("OTROS", "Otros"),
                        ],
                        default="BBVA",
                        max_length=12,
                    ),
                ),
                ("comision_cuenta_otro", models.CharField(blank=True, max_length=100)),
                ("observaciones_generales", models.TextField(blank=True)),
                ("fecha_propuesta", models.DateField(auto_now_add=True)),
                (
                    "estado_pago_actual",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("con_adelantos", "Con adelantos"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "total_adelantado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "total_cancelado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "total_pagado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propuestas_actualizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propuestas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propuestas_borradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="propuestas",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropuestaMovimientoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("adelanto", "Adelanto"),
                            ("cancelacion", "Cancelación"),
                        ],
                        max_length=20,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
                ("fecha", models.DateField()),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "medio_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("cheque", "Cheque"),
                            ("deposito", "Depósito"),
                        ],
                        max_length=10,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "tipo_comprobante",
                    models.CharField(
                        choices=[
                            ("RH", "RH"),
                            ("FACTURA", "Factura"),
                            ("SIN", "Sin comprobante"),
                        ],
                        default="SIN",
                        max_length=10,
                    ),
                ),
                ("rh_tiene_retencion", models.BooleanField(default=False)),
                (
                    "rh_retencion_monto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "factura_modalidad",
                    models.CharField(
                        blank=True,
                        choices=[("contado", "Contado"), ("credito", "Crédito")],
                        max_length=10,
                    ),
                ),
                ("factura_fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "factura_credito_cancelado",
                    models.BooleanField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "propuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="propuestas.propuesta",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="PropuestaDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("propuesta_general", "Propuesta general"),
                            ("movimiento_soporte", "Soporte de movimiento"),
                            ("rh_retencion", "RH retención"),
                            ("factura", "Factura"),
                            ("detraccion", "Detracción"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=propuestas.models.propuesta_document_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                ("nombre_original", models.CharField(blank=True, max_length=255)),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "propuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="propuestas.propuesta",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_propuesta_subidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "movimiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="propuestas.propuestamovimientopago",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PropuestaRelacionCartaFianza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
                ("snapshot_numero_carta", models.CharField(blank=True, max_length=50)),
                ("snapshot_aseguradora", models.CharField(blank=True, max_length=100)),
                ("snapshot_tipo_carta", models.CharField(blank=True, max_length=100)),
                (
                    "snapshot_monto",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "snapshot_entidad_beneficiaria",
                    models.CharField(blank=True, max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "carta_fianza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="propuestas_relacionadas",
                        to="empresas.cartafianza",
                    ),
                ),
                (
                    "propuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relaciones_cartas",
                        to="propuestas.propuesta",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="PropuestaRelacionFideicomiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
                ("snapshot_fiduciaria", models.CharField(blank=True, max_length=200)),
                ("snapshot_ejecutora", models.CharField(blank=True, max_length=200)),
                (
                    "snapshot_representante",
                    models.CharField(blank=True, max_length=200),
                ),
                ("snapshot_residente", models.CharField(blank=True, max_length=200)),
                ("snapshot_estado", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fideicomiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="propuestas_relacionadas",
                        to="empresas.fideicomiso",
                    ),
                ),
                (
                    "propuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relaciones_fideicomisos",
                        to="propuestas.propuesta",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="propuesta",
            index=models.Index(
                fields=["empresa"], name="propuestas__empresa_3acd72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propuesta",
            index=models.Index(
                fields=["tipo_propuesta"], name="propuestas__tipo_pr_f7f065_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propuesta",
            index=models.Index(
                fields=["estado_pago_actual"], name="propuestas__estado__dda902_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propuesta",
            index=models.Index(
                fields=["fecha_propuesta"], name="propuestas__fecha_p_a0c754_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propuesta",
            index=models.Index(
                fields=["is_deleted"], name="propuestas__is_dele_940cb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propuestamovimientopago",
            index=models.Index(
                fields=["propuesta"], name="propuestas__propues_2950b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propuestamovimientopago",
            index=models.Index(
                fields=["tipo_movimiento"], name="propuestas__tipo_mo_3a61fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propuestamovimientopago",
            index=models.Index(fields=["fecha"], name="propuestas__fecha_30a5c9_idx"),
        ),
        migrations.AddIndex(
            model_name="propuestamovimientopago",
            index=models.Index(
                fields=["tipo_comprobante"], name="propuestas__tipo_co_dc105d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="propuestarelacioncartafianza",
            constraint=models.UniqueConstraint(
                fields=("propuesta", "carta_fianza"), name="uq_propuesta_carta_fianza"
            ),
        ),
        migrations.AddConstraint(
            model_name="propuestarelacioncartafianza",
            constraint=models.UniqueConstraint(
                fields=("propuesta", "orden"), name="uq_propuesta_carta_orden"
            ),
        ),
        migrations.AddConstraint(
            model_name="propuestarelacionfideicomiso",
            constraint=models.UniqueConstraint(
                fields=("propuesta", "fideicomiso"), name="uq_propuesta_fideicomiso"
            ),
        ),
        migrations.AddConstraint(
            model_name="propuestarelacionfideicomiso",
            constraint=models.UniqueConstraint(
                fields=("propuesta", "orden"), name="uq_propuesta_fideicomiso_orden"
            ),
        ),
    ]
