# Generated by Django 5.1.7 on 2026-03-26 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propuestas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="propuesta",
            name="consorcio_integrantes_snapshot",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="propuesta",
            name="entidad",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="propuesta",
            name="facturador_texto",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Debes ingresar un RUC válido de 11 dígitos.",
                        regex="^\\d{11}$",
                    )
                ],
            ),
        ),
    ]
