# Generated by Django 5.1.7 on 2026-03-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propuestas", "0002_propuesta_consorcio_integrantes_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propuesta",
            name="tipos_relacionados",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tipos seleccionados manualmente para la propuesta.",
                max_length=50,
            ),
        ),
    ]
