# Generated by Django 5.1.7 on 2025-03-24 18:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ruc",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El RUC debe tener exactamente 11 dígitos numéricos.",
                                regex="^\\d{11}$",
                            )
                        ],
                        verbose_name="RUC",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Empresa"
                    ),
                ),
                (
                    "nombre_gerente",
                    models.CharField(max_length=100, verbose_name="Nombre del Gerente"),
                ),
                (
                    "dni_gerente",
                    models.CharField(max_length=8, verbose_name="DNI del Gerente"),
                ),
                (
                    "telefono",
                    models.CharField(max_length=15, verbose_name="Número de Teléfono"),
                ),
                (
                    "correo",
                    models.EmailField(
                        max_length=254, verbose_name="Correo Electrónico"
                    ),
                ),
                (
                    "consorciados",
                    models.TextField(blank=True, verbose_name="Consorciados"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("archivo_pdf", models.FileField(upload_to="cartas_fianza/")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                    ),
                ),
            ],
        ),
    ]
