# Generated by Django 5.1.7 on 2025-03-25 02:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="consorciados",
        ),
        migrations.AlterField(
            model_name="empresa",
            name="dni_gerente",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Solo se permiten números.", regex="^\\d+$"
                    )
                ],
                verbose_name="DNI/C.E. del Gerente",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="telefono",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El número de teléfono debe tener 9 dígitos.",
                        regex="^\\d{9}$",
                    )
                ],
                verbose_name="Número de Teléfono",
            ),
        ),
        migrations.CreateModel(
            name="CartaFianza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aseguradora",
                    models.CharField(
                        choices=[
                            ("SECREX", "SECREX"),
                            ("INSUR", "INSUR"),
                            ("CRECER", "CRECER"),
                            ("AVLA", "AVLA"),
                            ("OTROS", "OTROS"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "numero_fianza",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Solo se permiten números.", regex="^\\d+$"
                            )
                        ],
                    ),
                ),
                (
                    "tipo_carta",
                    models.CharField(
                        choices=[
                            ("ADELANTO DE MATERIALES", "ADELANTO DE MATERIALES"),
                            ("ADELANTO DIRECTO", "ADELANTO DIRECTO"),
                            ("FIEL CUMPLIMIENTO", "FIEL CUMPLIMIENTO"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[("S/", "Soles"), ("$", "Dólares"), ("€", "Euros")],
                        max_length=3,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("plazo_meses", models.PositiveIntegerField()),
                ("plazo_dias", models.PositiveIntegerField()),
                ("fecha_vencimiento", models.DateField()),
                ("entidad", models.CharField(max_length=100)),
                ("tiene_consorcio", models.BooleanField(default=False)),
                ("nombre_consorcio", models.CharField(blank=True, max_length=100)),
                ("empresas_consorciadas", models.TextField(blank=True)),
                ("representante_legal", models.CharField(blank=True, max_length=100)),
                ("dni_representante", models.CharField(blank=True, max_length=15)),
                ("archivo_pdf", models.FileField(upload_to="cartas_fianza/")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartas_fianza",
                        to="empresas.empresa",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Archivo",
        ),
    ]
