# Generated by Django 5.1.7 on 2025-03-25 18:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0002_remove_empresa_consorciados_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartafianza",
            name="archivo_pdf",
            field=models.FileField(
                upload_to="cartas_fianza/", verbose_name="Archivo PDF"
            ),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="aseguradora",
            field=models.CharField(
                choices=[
                    ("SECREX", "SECREX"),
                    ("INSUR", "INSUR"),
                    ("CRECER", "CRECER"),
                    ("AVLA", "AVLA"),
                    ("OTROS", "OTROS"),
                ],
                max_length=10,
                verbose_name="Aseguradora",
            ),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="dni_representante",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Solo se permiten números.", regex="^\\d+$"
                    )
                ],
                verbose_name="DNI/C.E. del Representante",
            ),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartas_fianza",
                to="empresas.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="empresas_consorciadas",
            field=models.TextField(
                blank=True, verbose_name="Empresas Consorciadas y Porcentaje"
            ),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="entidad",
            field=models.CharField(max_length=100, verbose_name="Entidad"),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="fecha_vencimiento",
            field=models.DateField(verbose_name="Fecha de Vencimiento"),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="moneda",
            field=models.CharField(
                choices=[("S/", "Soles"), ("$", "Dólares"), ("€", "Euros")],
                max_length=3,
                verbose_name="Moneda",
            ),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="monto",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Monto"
            ),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="nombre_consorcio",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nombre del Consorcio"
            ),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="numero_fianza",
            field=models.CharField(max_length=20, verbose_name="Número de Fianza"),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="plazo_dias",
            field=models.PositiveIntegerField(verbose_name="Plazo (Días)"),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="plazo_meses",
            field=models.PositiveIntegerField(verbose_name="Plazo (Meses)"),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="representante_legal",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Representante Legal"
            ),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="tiene_consorcio",
            field=models.BooleanField(default=False, verbose_name="¿Tiene Consorcio?"),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="tipo_carta",
            field=models.CharField(
                choices=[
                    ("ADELANTO DE MATERIALES", "ADELANTO DE MATERIALES"),
                    ("ADELANTO DIRECTO", "ADELANTO DIRECTO"),
                    ("FIEL CUMPLIMIENTO", "FIEL CUMPLIMIENTO"),
                ],
                max_length=30,
                verbose_name="Tipo de Carta",
            ),
        ),
    ]
