# Generated by Django 5.1.7 on 2025-03-25 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0003_alter_cartafianza_archivo_pdf_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivoAdjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="cartas_fianza/")),
                (
                    "carta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="empresas.cartafianza",
                    ),
                ),
            ],
        ),
    ]
