# Generated by Django 5.1.7 on 2025-03-26 05:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0004_archivoadjunto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartafianza",
            name="archivo_pdf",
        ),
        migrations.DeleteModel(
            name="ArchivoAdjunto",
        ),
    ]
