# Generated by Django 5.1.7 on 2025-03-26 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0005_remove_cartafianza_archivo_pdf_delete_archivoadjunto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fideicomiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entidad_fiduciaria", models.CharField(max_length=100)),
                ("representante", models.CharField(max_length=100)),
                (
                    "adelanto_directo_moneda",
                    models.CharField(
                        choices=[("S/", "Soles"), ("$", "Dólares"), ("€", "Euros")],
                        max_length=3,
                    ),
                ),
                (
                    "adelanto_directo_monto",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "adelanto_materiales_moneda",
                    models.CharField(
                        choices=[("S/", "Soles"), ("$", "Dólares"), ("€", "Euros")],
                        max_length=3,
                    ),
                ),
                (
                    "adelanto_materiales_monto",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("residente_obra", models.CharField(max_length=100)),
                ("estado_ejecucion", models.CharField(max_length=100)),
                ("modalidad_ejecucion", models.CharField(max_length=100)),
                (
                    "monto_contrato",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_termino", models.DateField()),
                ("desembolsos_mensuales", models.TextField(blank=True)),
                ("avances_curva_s", models.TextField(blank=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fideicomisos",
                        to="empresas.empresa",
                    ),
                ),
            ],
        ),
    ]
