# Generated by Django 5.1.7 on 2025-03-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0006_fideicomiso"),
    ]

    operations = [
        migrations.AddField(
            model_name="fideicomiso",
            name="monto_contrato_moneda",
            field=models.CharField(
                choices=[("S/", "Soles"), ("$", "Dólares"), ("€", "Euros")],
                default="S/",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="fideicomiso",
            name="adelanto_directo_moneda",
            field=models.CharField(
                choices=[("S/", "Soles"), ("$", "Dólares"), ("€", "Euros")],
                default="S/",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="fideicomiso",
            name="adelanto_materiales_moneda",
            field=models.CharField(
                choices=[("S/", "Soles"), ("$", "Dólares"), ("€", "Euros")],
                default="S/",
                max_length=3,
            ),
        ),
    ]
