# Generated by Django 5.1.7 on 2025-03-27 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0007_fideicomiso_monto_contrato_moneda_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivoAdjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="archivos_adjunto/")),
                (
                    "carta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="empresas.cartafianza",
                    ),
                ),
                (
                    "fideicomiso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="empresas.fideicomiso",
                    ),
                ),
            ],
        ),
    ]
