# Generated by Django 5.1.7 on 2025-03-27 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0008_archivoadjunto"),
    ]

    operations = [
        migrations.AddField(
            model_name="fideicomiso",
            name="dni_representante",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Solo se permiten números.", regex="^\\d+$"
                    )
                ],
                verbose_name="DNI/C.E. del Representante",
            ),
        ),
        migrations.AddField(
            model_name="fideicomiso",
            name="empresas_consorciadas",
            field=models.TextField(
                blank=True, verbose_name="Empresas Consorciadas y Porcentaje"
            ),
        ),
        migrations.AddField(
            model_name="fideicomiso",
            name="nombre_consorcio",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nombre del Consorcio"
            ),
        ),
        migrations.AddField(
            model_name="fideicomiso",
            name="representante_legal",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Representante Legal"
            ),
        ),
        migrations.AddField(
            model_name="fideicomiso",
            name="tiene_consorcio",
            field=models.BooleanField(default=False, verbose_name="¿Tiene Consorcio?"),
        ),
    ]
