# Generated by Django 5.1.7 on 2025-03-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0009_fideicomiso_dni_representante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fideicomiso",
            name="entidad_ejecutora",
            field=models.CharField(default="Sin especificar", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fideicomiso",
            name="plazo_ejecucion",
            field=models.CharField(default="Sin especificar", max_length=50),
            preserve_default=False,
        ),
    ]
