# Generated by Django 5.1.7 on 2025-05-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0010_fideicomiso_entidad_ejecutora_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="correo_envio",
            field=models.EmailField(
                blank=True,
                help_text="Dirección donde llegarán las notificaciones automáticas",
                max_length=254,
                null=True,
                verbose_name="Correo de envío",
            ),
        ),
    ]
