# Generated by Django 5.1.7 on 2025-05-14 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0011_empresa_correo_envio"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartafianza",
            name="afianzado",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Afianzado"
            ),
        ),
        migrations.AddField(
            model_name="cartafianza",
            name="aseguradora_otro",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Especifique la aseguradora",
            ),
        ),
        migrations.AddField(
            model_name="cartafianza",
            name="es_independiente",
            field=models.BooleanField(default=False, verbose_name="¿Es Independiente?"),
        ),
        migrations.AddField(
            model_name="cartafianza",
            name="ruc_consorcio",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{11}$",
                        "El RUC debe tener exactamente 11 dígitos numéricos.",
                    )
                ],
                verbose_name="RUC Consorcio",
            ),
        ),
        migrations.AddField(
            model_name="cartafianza",
            name="ruc_tributador",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{11}$",
                        "El RUC debe tener exactamente 11 dígitos numéricos.",
                    )
                ],
                verbose_name="RUC Tributador",
            ),
        ),
        migrations.AddField(
            model_name="cartafianza",
            name="tributador",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Tributador"
            ),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="aseguradora",
            field=models.CharField(
                choices=[
                    ("SECREX", "SECREX"),
                    ("INSUR", "INSUR"),
                    ("CRECER", "CRECER"),
                    ("AVLA", "AVLA"),
                    ("FONDO_MI_VIVIENDA", "FIEL CUMPLIENTO DE FONDO MI VIVIENDA"),
                    ("OTROS", "OTROS"),
                ],
                max_length=30,
                verbose_name="Aseguradora",
            ),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="dni_representante",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Solo se permiten números."
                    )
                ],
                verbose_name="DNI/C.E. del Representante",
            ),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="entidad",
            field=models.CharField(max_length=100, verbose_name="Entidad/Beneficiario"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="dni_gerente",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Solo se permiten números."
                    )
                ],
                verbose_name="DNI/C.E. del Gerente",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="ruc",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{11}$",
                        "El RUC debe tener exactamente 11 dígitos numéricos.",
                    )
                ],
                verbose_name="RUC",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="telefono",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{9}$", "El número de teléfono debe tener 9 dígitos."
                    )
                ],
                verbose_name="Número de Teléfono",
            ),
        ),
        migrations.AlterField(
            model_name="fideicomiso",
            name="dni_representante",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Solo se permiten números."
                    )
                ],
                verbose_name="DNI/C.E. del Representante",
            ),
        ),
    ]
