# Generated by Django 5.1.7 on 2025-05-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "empresas",
            "0012_cartafianza_afianzado_cartafianza_aseguradora_otro_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartafianza",
            name="aseguradora",
            field=models.CharField(
                choices=[
                    ("SECREX", "SECREX"),
                    ("INSUR", "INSUR"),
                    ("CRECER", "CRECER"),
                    ("AVLA", "AVLA"),
                    ("OTROS", "OTROS"),
                ],
                max_length=30,
                verbose_name="Aseguradora",
            ),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="tipo_carta",
            field=models.CharField(
                choices=[
                    ("ADELANTO DE MATERIALES", "ADELANTO DE MATERIALES"),
                    ("ADELANTO DIRECTO", "ADELANTO DIRECTO"),
                    ("FIEL CUMPLIMIENTO", "FIEL CUMPLIMIENTO"),
                    ("FONDO_MI_VIVIENDA", "FIEL CUMPLIENTO DE FONDO MI VIVIENDA"),
                ],
                max_length=30,
                verbose_name="Tipo de Carta",
            ),
        ),
    ]
