# Generated by Django 5.1.7 on 2025-05-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0013_alter_cartafianza_aseguradora_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fideicomiso",
            name="tributador_banco",
            field=models.CharField(default="", max_length=100, verbose_name="Banco"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fideicomiso",
            name="tributador_nombre",
            field=models.CharField(
                default="NO-ASIGNADO",
                max_length=100,
                verbose_name="Nombre del Tributador",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fideicomiso",
            name="tributador_nro_cci",
            field=models.CharField(
                default="NO-ASIGNADO", max_length=30, verbose_name="Nro. de Cuenta CCI"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fideicomiso",
            name="tributador_nro_cuenta",
            field=models.CharField(
                default="NO-ASIGNADO", max_length=30, verbose_name="Nro. de Cuenta"
            ),
            preserve_default=False,
        ),
    ]
