# Generated by Django 5.1.7 on 2025-05-15 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0014_fideicomiso_tributador_banco_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Desembolso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("DIRECTO", "Directo"), ("MATERIALES", "Materiales")],
                        max_length=11,
                    ),
                ),
                ("fecha", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "fideicomiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desembolsos",
                        to="empresas.fideicomiso",
                    ),
                ),
            ],
        ),
    ]
