# Generated by Django 5.1.7 on 2025-05-22 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0015_desembolso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="correo",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Correo Electrónico"
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="telefono",
            field=models.CharField(
                blank=True,
                max_length=9,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{9}$", "El número de teléfono debe tener 9 dígitos."
                    )
                ],
                verbose_name="Número de Teléfono",
            ),
        ),
    ]
