# Generated by Django 5.1.7 on 2025-05-22 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0016_alter_empresa_correo_alter_empresa_telefono"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fideicomiso",
            name="dni_representante",
        ),
        migrations.RemoveField(
            model_name="fideicomiso",
            name="empresas_consorciadas",
        ),
        migrations.RemoveField(
            model_name="fideicomiso",
            name="nombre_consorcio",
        ),
        migrations.RemoveField(
            model_name="fideicomiso",
            name="representante_legal",
        ),
        migrations.RemoveField(
            model_name="fideicomiso",
            name="tiene_consorcio",
        ),
    ]
