# Generated by Django 5.1.7 on 2025-05-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0017_remove_fideicomiso_dni_representante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartafianza",
            name="numero_adicional",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Si es un adicional > 1, escríbelo en números romanos (II, III…)",
                null=True,
                verbose_name="Número de adicional",
            ),
        ),
        migrations.AlterField(
            model_name="cartafianza",
            name="tipo_carta",
            field=models.CharField(
                choices=[
                    ("ADELANTO DE MATERIALES", "ADELANTO DE MATERIALES"),
                    ("ADELANTO DIRECTO", "ADELANTO DIRECTO"),
                    ("FIEL CUMPLIMIENTO", "FIEL CUMPLIMIENTO"),
                    ("FONDO_MI_VIVIENDA", "FIEL CUMPLIENTO DE FONDO MI VIVIENDA"),
                    ("FIEL CUMPLIMIENTO – ADICIONAL", "FIEL CUMPLIMIENTO – ADICIONAL"),
                ],
                max_length=30,
                verbose_name="Tipo de Carta",
            ),
        ),
    ]
