# Generated by Django 5.1.7 on 2025-05-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0018_cartafianza_numero_adicional_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="socios",
            field=models.TextField(
                blank=True,
                help_text="Se completa automáticamente desde el formulario",
                verbose_name="Socios (% y DNI/C.E.)",
            ),
        ),
    ]
