# Generated by Django 5.1.7 on 2025-05-23 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0019_empresa_socios"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagoEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[("S/", "Soles"), ("$", "Dólares"), ("€", "Euros")],
                        max_length=3,
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto total"
                    ),
                ),
                (
                    "cancelado",
                    models.BooleanField(default=False, verbose_name="¿Cancelado?"),
                ),
                (
                    "tipo_comprobante",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FACTURA", "Factura"),
                            ("RECIBO", "Recibo por honorarios"),
                            ("NINGUNO", "Ninguno"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de comprobante",
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de pago"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago a Empresa",
                "verbose_name_plural": "Pagos a Empresa",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="pagos_adjuntos/", verbose_name="Documento de pago"
                    ),
                ),
                (
                    "pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="empresas.pagoempresa",
                        verbose_name="Pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Pago",
                "verbose_name_plural": "Documentos de Pago",
            },
        ),
        migrations.CreateModel(
            name="AdelantoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Monto del adelanto",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha del adelanto")),
                (
                    "pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adelantos",
                        to="empresas.pagoempresa",
                        verbose_name="Pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adelanto de Pago",
                "verbose_name_plural": "Adelantos de Pago",
                "ordering": ["fecha"],
            },
        ),
    ]
