# Generated by Django 5.1.7 on 2025-05-29 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0020_pagoempresa_documentopago_adelantopago"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fideicomiso",
            name="avances_curva_s",
        ),
        migrations.RemoveField(
            model_name="fideicomiso",
            name="desembolsos_mensuales",
        ),
        migrations.AddField(
            model_name="fideicomiso",
            name="deuda_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="fideicomiso",
            name="resta_pendiente",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.CreateModel(
            name="AdelantoFid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(blank=True, null=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "fideicomiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adelantos",
                        to="empresas.fideicomiso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorreoFideicomiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "propietario",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Propietario"
                    ),
                ),
                ("correo", models.EmailField(max_length=254, verbose_name="Correo")),
                (
                    "fideicomiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correos",
                        to="empresas.fideicomiso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoFid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("desembolso", "Desembolsos mensuales"),
                            ("curva_s", "Curva S"),
                            ("fact_sustentacion", "Factura sustentación"),
                            ("fact_fiduciaria", "Factura fiduciaria"),
                            ("fact_control", "Factura supervisión-control"),
                            ("sust_mensual", "Sustentos mensuales"),
                            ("sust_obra", "Sustentos de obra"),
                            ("carta_lib", "Cartas de liberación"),
                            ("cronograma", "Cronograma de pago"),
                        ],
                        max_length=20,
                    ),
                ),
                ("archivo", models.FileField(upload_to="fideicomiso_docs/")),
                (
                    "fideicomiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="empresas.fideicomiso",
                    ),
                ),
            ],
        ),
    ]
