# Generated by Django 5.1.7 on 2025-05-29 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0021_remove_fideicomiso_avances_curva_s_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartafianza",
            name="liquidada",
            field=models.BooleanField(default=False, verbose_name="¿Liquidada?"),
        ),
        migrations.CreateModel(
            name="LiquidacionFianza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto_dev",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Monto total de devolución",
                    ),
                ),
                (
                    "aseguradora",
                    models.CharField(
                        choices=[
                            ("SECREX", "SECREX"),
                            ("INSUR", "INSUR"),
                            ("CRECER", "CRECER"),
                            ("AVLA", "AVLA"),
                            ("OTROS", "OTROS"),
                        ],
                        max_length=30,
                        verbose_name="Aseguradora",
                    ),
                ),
                ("fecha_dev", models.DateField(verbose_name="Fecha de devolución")),
                (
                    "nro_fianza",
                    models.CharField(max_length=20, verbose_name="Nº de Fianza"),
                ),
                (
                    "documentos",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="liquidacion_fianzas/",
                        verbose_name="Documentos de liquidación",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "carta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidacion",
                        to="empresas.cartafianza",
                        verbose_name="Carta Fianza",
                    ),
                ),
            ],
        ),
    ]
