# Generated by Django 5.1.7 on 2025-05-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0022_cartafianza_liquidada_liquidacionfianza"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="dni_representante",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="empresa",
            name="empresas_consorciadas",
            field=models.TextField(
                blank=True, help_text="Lista de empresas + % (suma=100%)"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="es_consorcio",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empresa",
            name="es_independiente",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empresa",
            name="nombre_consorcio",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="empresa",
            name="representante_legal",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="empresa",
            name="ruc_consorcio",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name="empresa",
            name="ruc_tributador",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name="empresa",
            name="tributador",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
