# Generated by Django 5.1.7 on 2025-05-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0023_empresa_dni_representante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fideicomiso",
            name="deuda_total_moneda",
            field=models.CharField(
                choices=[("S/", "Soles"), ("$", "Dólares"), ("€", "Euros")],
                default="S/",
                max_length=3,
                verbose_name="Moneda de los pagos",
            ),
        ),
    ]
