# Generated by Django 5.1.7 on 2025-05-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0024_fideicomiso_deuda_total_moneda"),
    ]

    operations = [
        migrations.AddField(
            model_name="fideicomiso",
            name="dni_representante",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="fideicomiso",
            name="empresas_consorciadas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fideicomiso",
            name="es_independiente",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fideicomiso",
            name="nombre_consorcio",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="fideicomiso",
            name="representante_legal",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="fideicomiso",
            name="ruc_consorcio",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name="fideicomiso",
            name="tiene_consorcio",
            field=models.BooleanField(default=False),
        ),
    ]
