# Generated by Django 5.1.7 on 2025-10-02 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0025_fideicomiso_dni_representante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagoempresa",
            name="carta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagos",
                to="empresas.cartafianza",
            ),
        ),
        migrations.AddField(
            model_name="pagoempresa",
            name="fideicomiso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagos",
                to="empresas.fideicomiso",
            ),
        ),
        migrations.AddField(
            model_name="pagoempresa",
            name="origen",
            field=models.CharField(
                choices=[("CARTA", "Cartas Fianza"), ("FIDEI", "Fideicomisos")],
                default="CARTA",
                max_length=5,
            ),
        ),
    ]
