# Generated by Django 5.1.7 on 2025-10-03 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0026_pagoempresa_carta_pagoempresa_fideicomiso_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvisoVencimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days_before", models.PositiveSmallIntegerField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("recipients", models.TextField(blank=True)),
                (
                    "subject",
                    models.CharField(
                        default="¡TU FIANZA ESTA A PUNTO DE VENCER!", max_length=200
                    ),
                ),
                (
                    "carta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avisos",
                        to="empresas.cartafianza",
                    ),
                ),
            ],
            options={
                "ordering": ("-sent_at",),
                "unique_together": {("carta", "days_before")},
            },
        ),
    ]
