# Generated by Django 5.1.7 on 2026-03-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0027_avisovencimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="observaciones",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Notas opcionales de la empresa o consorcio",
                verbose_name="Observaciones",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="correo_envio",
            field=models.TextField(
                blank=True,
                help_text="Direcciones separadas por coma o punto y coma",
                null=True,
                verbose_name="Correos de envío",
            ),
        ),
    ]
