# Generated by Django 5.1.7 on 2026-03-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0028_empresa_observaciones_alter_empresa_correo_envio"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartafianza",
            name="empresas_relacionadas",
            field=models.ManyToManyField(
                blank=True,
                related_name="cartas_fianza_relacionadas",
                to="empresas.empresa",
                verbose_name="Empresas relacionadas por consorcio",
            ),
        ),
    ]
