# Generated by Django 5.1.7 on 2026-03-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0029_cartafianza_empresas_relacionadas"),
    ]

    operations = [
        migrations.AddField(
            model_name="fideicomiso",
            name="empresas_relacionadas",
            field=models.ManyToManyField(
                blank=True,
                related_name="fideicomisos_relacionados",
                to="empresas.empresa",
                verbose_name="Empresas relacionadas por consorcio",
            ),
        ),
    ]
